language: node_js
node_js:
  - v6
cache:
  yarn: true
services:
  - mongodb
before_install:
  - cd tests/test-chai
  - openssl aes-256-cbc -K $encrypted_677f205b7cff_key -iv $encrypted_677f205b7cff_iv -in .env.enc -out .env -d
before_script:
  - npm install -g yarn
  - yarn
  - cd ../../servers/server-express
  - npm install
  - cd ../../tests/test-chai
script:
  - npm test
addons:
  code_climate:
    repo_token: 212c607f23a9eee424108f3171bfee6d2eb3292091e3f1f8ff35360d075ca9a0
